stages:
  fetch:
    cmd: python /path/to/fetch_weather.py
    deps:
      - /path/to/fetch_weather.py
    outs:
      - raw_data.csv

  preprocess:
    cmd: python /path/to/preprocess.py
    deps:
      - /path/to/preprocess.py
      - raw_data.csv
    outs:
      - processed_data.csv

  train:
    cmd: python train_model.py
    deps:
      - model.py
      - processed_data.csv
    outs:
      - model.pkl
