name: CD Pipeline

on:
  push:
    branches:
      - prod    # Trigger CD for prod branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Log in to DockerHub
      - name: Login to DockerHub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Build backend Docker image
      - name: Build backend Docker image
        run: |
          docker build -t fatimaimran/weather-project-backend . # Adjust the path if needed

      # Build frontend Docker image
      - name: Build frontend Docker image
        run: |
          docker build -t fatimaimran/weather-project-frontend . # Adjust the path if needed

      # Push backend Docker image to DockerHub
      - name: Push backend Docker image
        run: |
          docker push fatimaimran/weather-project-backend

      # Push frontend Docker image to DockerHub
      - name: Push frontend Docker image
        run: |
          docker push fatimaimran/weather-project-frontend

      # Set up kubectl for Minikube
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'  # Install the latest version of kubectl

      # Deploy to Minikube (or your target Kubernetes environment)
      - name: Deploy to Minikube
        run: |
          kubectl config use-context minikube  # Switch context to Minikube
          
         

      # Optional: Check if the services are running properly in Minikube
      - name: Check Minikube services
        run: |
          kubectl get pods
          kubectl get services
